/**
 * Every user-facing string of the phone web-remote, in the app's three
 * languages. Static HTML uses ${t.*} at render time; the runtime script gets
 * the whole language's dict injected as `L` (see webRemotePage.ts).
 *
 * Keep the three languages key-identical — the parity test enforces it.
 */

export type RemoteLang = 'pt' | 'en' | 'es'

// Every user-facing string of the phone page, in the app's three languages.
// Static HTML uses ${t.*}; the runtime script gets the whole dict as `L`.
export const STRINGS: Record<RemoteLang, Record<string, string>> = {
    pt: {
        htmlLang: 'pt-BR', brandSuffix: 'Controle',
        pinTitle: 'Digite o PIN', pinHint: 'O c\u00f3digo aparece em Configura\u00e7\u00f5es \u2192 Rede no computador',
        pinConnect: 'Conectar', pinWrong: 'PIN incorreto. Confira o c\u00f3digo no computador.', pinLen: 'O PIN tem 4 d\u00edgitos.',
        tabControl: 'Controle', tabGuide: 'Guia', tabMovies: 'Filmes', tabSeries: 'S\u00e9ries', tabContinue: 'Continuar',
        castTo: 'Transmitir em', devAuto: 'Autom\u00e1tico (1\u00aa TV)',
        searchAllPh: 'Buscar filmes e s\u00e9ries\u2026', searchPrompt: 'Digite para buscar no acervo.', searching: 'Buscando\u2026', noResults: 'Nenhum resultado.',
        connecting: 'Conectando\u2026', connected: 'Conectado', reconnecting: 'Reconectando\u2026',
        prev: 'Anterior', playPause: 'Play/Pause', next: 'Pr\u00f3ximo', volDown: 'Volume -', mute: 'Mudo', volUp: 'Volume +',
        subtitle: 'Legenda', audio: '\u00c1udio', stop: 'Parar',
        hint: 'Mantenha o app aberto no computador. Este controle funciona na mesma rede Wi-Fi.',
        nowOnTv: 'Agora na TV', noChannel: 'Nenhum canal tocando', searchChannel: 'Buscar canal\u2026',
        guideEmpty: 'Abra a <b>TV ao vivo</b> no computador para ver os canais aqui.',
        searchMovie: 'Buscar filme\u2026', loadingMovies: 'Carregando filmes\u2026', noMovies: 'Nenhum filme.', noMovieFound: 'Nenhum filme encontrado.',
        castQueue: 'Transmitir fila',
        searchSeries: 'Buscar s\u00e9rie\u2026', loadingSeries: 'Carregando s\u00e9ries\u2026', noSeries: 'Nenhuma s\u00e9rie.', noSeriesFound: 'Nenhuma s\u00e9rie encontrada.',
        seeEpisodes: 'Ver epis\u00f3dios', back: 'Voltar', loadingEpisodes: 'Carregando epis\u00f3dios\u2026', noEpisodes: 'Nenhum epis\u00f3dio.',
        loading: 'Carregando\u2026', nothingInProgress: 'Nada em andamento.', resumeOnTv: 'Retomar na TV', castToTv: 'Transmitir na TV',
        becauseWatched: 'Porque voc\u00ea assistiu',
        playing: 'Reproduzindo', paused: 'Pausado', nothingPlaying: 'Nada tocando', castingOnTv: 'Transmitindo na TV',
        castingToast: 'Transmitindo', onDevice: ' em ', noTvFound: 'Nenhuma TV encontrada na rede', castFailed: 'Falha ao transmitir',
        nextUp: 'A seguir: ', noInfo: 'Sem informa\u00e7\u00e3o', noChannelFound: 'Nenhum canal encontrado.', programming: 'Programa\u00e7\u00e3o',
        recTitle: 'Gravar no computador', recStarted: 'Gravando', recFail: 'Falha ao iniciar a gravação',
        recStop: 'Parar gravação', recStopped: 'Gravação encerrada', schedNext: 'Gravar o próximo', schedOk: 'Agendado: ', schedFail: 'Não deu pra agendar (sem programação?)',
        recCardTitle: 'Gravações', recReady: 'Prontas no computador',
        recDelete: 'Excluir gravação', recDeleteConfirm: 'Toque de novo pra confirmar', recDeleted: 'Gravação excluída',
    },
    en: {
        htmlLang: 'en', brandSuffix: 'Remote',
        pinTitle: 'Enter the PIN', pinHint: 'The code is shown under Settings \u2192 Network on the computer',
        pinConnect: 'Connect', pinWrong: 'Wrong PIN. Check the code on the computer.', pinLen: 'The PIN has 4 digits.',
        tabControl: 'Remote', tabGuide: 'Guide', tabMovies: 'Movies', tabSeries: 'Series', tabContinue: 'Continue',
        castTo: 'Cast to', devAuto: 'Automatic (1st TV)',
        searchAllPh: 'Search movies & series\u2026', searchPrompt: 'Type to search the library.', searching: 'Searching\u2026', noResults: 'No results.',
        connecting: 'Connecting\u2026', connected: 'Connected', reconnecting: 'Reconnecting\u2026',
        prev: 'Previous', playPause: 'Play/Pause', next: 'Next', volDown: 'Volume -', mute: 'Mute', volUp: 'Volume +',
        subtitle: 'Subtitles', audio: 'Audio', stop: 'Stop',
        hint: 'Keep the app open on the computer. This remote works on the same Wi-Fi network.',
        nowOnTv: 'Now on TV', noChannel: 'No channel playing', searchChannel: 'Search channel\u2026',
        guideEmpty: 'Open <b>Live TV</b> on the computer to see the channels here.',
        searchMovie: 'Search movie\u2026', loadingMovies: 'Loading movies\u2026', noMovies: 'No movies.', noMovieFound: 'No movie found.',
        castQueue: 'Cast queue',
        searchSeries: 'Search series\u2026', loadingSeries: 'Loading series\u2026', noSeries: 'No series.', noSeriesFound: 'No series found.',
        seeEpisodes: 'View episodes', back: 'Back', loadingEpisodes: 'Loading episodes\u2026', noEpisodes: 'No episodes.',
        loading: 'Loading\u2026', nothingInProgress: 'Nothing in progress.', resumeOnTv: 'Resume on TV', castToTv: 'Cast to TV',
        becauseWatched: 'Because you watched',
        playing: 'Playing', paused: 'Paused', nothingPlaying: 'Nothing playing', castingOnTv: 'Casting to TV',
        castingToast: 'Casting', onDevice: ' on ', noTvFound: 'No TV found on the network', castFailed: 'Failed to cast',
        nextUp: 'Up next: ', noInfo: 'No information', noChannelFound: 'No channel found.', programming: 'Schedule',
        recTitle: 'Record on the computer', recStarted: 'Recording', recFail: 'Failed to start the recording',
        recStop: 'Stop recording', recStopped: 'Recording finished', schedNext: 'Record the next one', schedOk: 'Scheduled: ', schedFail: 'Could not schedule (no guide data?)',
        recCardTitle: 'Recordings', recReady: 'Ready on the computer',
        recDelete: 'Delete recording', recDeleteConfirm: 'Tap again to confirm', recDeleted: 'Recording deleted',
    },
    es: {
        htmlLang: 'es', brandSuffix: 'Control',
        pinTitle: 'Ingresa el PIN', pinHint: 'El c\u00f3digo aparece en Configuraci\u00f3n \u2192 Red en la computadora',
        pinConnect: 'Conectar', pinWrong: 'PIN incorrecto. Verifica el c\u00f3digo en la computadora.', pinLen: 'El PIN tiene 4 d\u00edgitos.',
        tabControl: 'Control', tabGuide: 'Gu\u00eda', tabMovies: 'Pel\u00edculas', tabSeries: 'Series', tabContinue: 'Continuar',
        castTo: 'Transmitir a', devAuto: 'Autom\u00e1tico (1\u00aa TV)',
        searchAllPh: 'Buscar pel\u00edculas y series\u2026', searchPrompt: 'Escribe para buscar en el cat\u00e1logo.', searching: 'Buscando\u2026', noResults: 'Sin resultados.',
        connecting: 'Conectando\u2026', connected: 'Conectado', reconnecting: 'Reconectando\u2026',
        prev: 'Anterior', playPause: 'Play/Pausa', next: 'Siguiente', volDown: 'Volumen -', mute: 'Silencio', volUp: 'Volumen +',
        subtitle: 'Subt\u00edtulos', audio: 'Audio', stop: 'Detener',
        hint: 'Mant\u00e9n la app abierta en la computadora. Este control funciona en la misma red Wi-Fi.',
        nowOnTv: 'Ahora en la TV', noChannel: 'Ning\u00fan canal en reproducci\u00f3n', searchChannel: 'Buscar canal\u2026',
        guideEmpty: 'Abre <b>TV en vivo</b> en la computadora para ver los canales aqu\u00ed.',
        searchMovie: 'Buscar pel\u00edcula\u2026', loadingMovies: 'Cargando pel\u00edculas\u2026', noMovies: 'No hay pel\u00edculas.', noMovieFound: 'No se encontr\u00f3 ninguna pel\u00edcula.',
        castQueue: 'Transmitir cola',
        searchSeries: 'Buscar serie\u2026', loadingSeries: 'Cargando series\u2026', noSeries: 'No hay series.', noSeriesFound: 'No se encontr\u00f3 ninguna serie.',
        seeEpisodes: 'Ver episodios', back: 'Volver', loadingEpisodes: 'Cargando episodios\u2026', noEpisodes: 'No hay episodios.',
        loading: 'Cargando\u2026', nothingInProgress: 'Nada en curso.', resumeOnTv: 'Reanudar en la TV', castToTv: 'Transmitir a la TV',
        becauseWatched: 'Porque viste',
        playing: 'Reproduciendo', paused: 'En pausa', nothingPlaying: 'Nada en reproducci\u00f3n', castingOnTv: 'Transmitiendo en la TV',
        castingToast: 'Transmitiendo', onDevice: ' en ', noTvFound: 'No se encontr\u00f3 ninguna TV en la red', castFailed: 'Error al transmitir',
        nextUp: 'A continuaci\u00f3n: ', noInfo: 'Sin informaci\u00f3n', noChannelFound: 'No se encontr\u00f3 ning\u00fan canal.', programming: 'Programaci\u00f3n',
        recTitle: 'Grabar en la computadora', recStarted: 'Grabando', recFail: 'Error al iniciar la grabación',
        recStop: 'Detener grabación', recStopped: 'Grabación finalizada', schedNext: 'Grabar el próximo', schedOk: 'Programado: ', schedFail: 'No se pudo programar (¿sin guía?)',
        recCardTitle: 'Grabaciones', recReady: 'Listas en la computadora',
        recDelete: 'Eliminar grabación', recDeleteConfirm: 'Toca de nuevo para confirmar', recDeleted: 'Grabación eliminada',
    },
}
